theme = "everforest_light"

[editor]
line-number = "absolute"
mouse = true
true-color = true
shell = ["/run/current-system/sw/bin/fish", "-c"]
gutters = [
  # basically turn off spacers
  "diagnostics", "line-numbers", "diff"
]
#bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render=true
skip-levels=1
